name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub contribution grid snake SVG
        run: |
          npx github-contributions-svgs
          mkdir dist
          mv *.svg dist/

      - name: Verify build directory
        run: |
          ls dist

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          allow_empty_commit: true
          commit_message: "Update GitHub Pages"
          token: ${{ secrets.Snake }}
